#!/usr/bin/env python3
"""scorecard.py — model-quality ledger for ADR implementation/scaffold reviews and issue-fix reviews.

Append one record per review (which model did the work, the verdict, finding counts,
Definition-of-Done pass rate) to a JSON ledger, then regenerate a markdown scorecard with
a per-model rollup — so models (sonnet-4.6, deepseek-v4-pro, gpt-5.4-mini, …) can be
compared at ADR-implementation quality over time.

Fairness rule baked in: only findings ATTRIBUTED TO THE MODEL count against its score.
A finding caused by a defect in the ADR itself (e.g. an unsatisfiable Definition of done)
or by the environment/tooling is still recorded — but excluded from the model's quality
metric. Scoring a model for an ADR bug would be unfair and pollute the comparison.

Usage:
  scorecard.py record --ledger docs/reviews/model-ledger.json \
      --adr 0001 --phase scaffold --model sonnet-4.6 --verdict changes-requested \
      --blockers 2 --majors 0 --minors 2 \
      --model-attributed 1 \
      --dod-passed 4 --dod-total 6 \
      --report docs/reviews/adr-0001-scaffold-sonnet-4.6.md \
      --notes "just ci exit 5 (ADR DoD self-contradiction, not model); flake.lock missing (model)"

  A fix review (the fix-review skill) is keyed on the issue instead of an ADR:
  scorecard.py record --ledger docs/reviews/model-ledger.json --issue 24 --phase fix ...

The one-line --notes is the at-a-glance summary; --report points at the full,
evidence-cited verdict doc the reviewer wrote (see references/review-method.md §4).
The rendered scorecard links each row to its report so the long form is one click away.

  scorecard.py render --ledger docs/reviews/model-ledger.json   # rewrite the sibling .md
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys
from collections import defaultdict

VERDICTS = ("pass", "changes-requested", "fail")
PHASES = ("scaffold", "implementation", "fix")


def load(ledger: str) -> list[dict]:
    if not os.path.exists(ledger):
        return []
    with open(ledger, encoding="utf-8") as f:
        return json.load(f)


def md_path(ledger: str) -> str:
    d = os.path.dirname(ledger) or "."
    return os.path.join(d, "model-scorecard.md")


def subject(r: dict) -> str:
    """The reviewed subject: an ADR number, #N for an issue fix, or <repo>#N for a language-repo issue."""
    return issue_ref(r["issue"]) if r.get("issue") else str(r.get("adr", ""))


def issue_ref(issue: str) -> str:
    return issue if "#" in issue else f"#{issue}"


def render(ledger: str) -> str:
    records = load(ledger)
    if not records:
        return "# Model scorecard\n\n_No reviews recorded yet._\n"

    by_model: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        by_model[r["model"]].append(r)

    def pct(num, den):
        return f"{100*num/den:.0f}%" if den else "—"

    lines = [
        "# Model scorecard — ADR implementation and fix quality",
        "",
        "_Generated by `scorecard.py` from `model-ledger.json` — do not hand-edit. Only "
        "**model-attributed** findings count against a model; findings caused by an ADR defect "
        "or the environment are recorded but excluded from the score._",
        "",
        "## Per-model rollup",
        "",
        "| Model | Reviews | Pass rate | Avg model findings/review | Avg DoD pass | ADRs / issues reviewed |",
        "|---|---|---|---|---|---|",
    ]
    for model in sorted(by_model):
        rs = by_model[model]
        n = len(rs)
        passes = sum(1 for r in rs if r.get("verdict") == "pass")
        avg_model_findings = sum(r.get("model_attributed", 0) for r in rs) / n
        dod_vals = [r["dod_passed"] / r["dod_total"] for r in rs if r.get("dod_total")]
        avg_dod = f"{100*sum(dod_vals)/len(dod_vals):.0f}%" if dod_vals else "—"
        adrs = ", ".join(sorted({subject(r) for r in rs}))
        lines.append(
            f"| {model} | {n} | {pct(passes, n)} | {avg_model_findings:.1f} | {avg_dod} | {adrs} |"
        )

    lines += [
        "",
        "_Pass rate = fraction of that model's reviews whose verdict was `pass` (no changes "
        "requested). Lower 'avg model findings/review' is better._",
        "",
        "## Review log (chronological)",
        "",
        "| Date | ADR / issue | Phase | Model | Verdict | B/M/m | Model-attrib | DoD | Report | Notes |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    base = os.path.dirname(md_path(ledger)) or "."
    for r in records:
        bmm = f"{r.get('blockers',0)}/{r.get('majors',0)}/{r.get('minors',0)}"
        dod = f"{r.get('dod_passed','?')}/{r.get('dod_total','?')}"
        notes = (r.get("notes", "") or "").replace("|", "\\|")
        if len(notes) > 90:
            notes = notes[:87] + "…"
        report = r.get("report", "") or ""
        report_cell = f"[report]({os.path.relpath(report, base)})" if report else "—"
        lines.append(
            f"| {r.get('date','')} | {subject(r)} | {r.get('phase','')} | {r['model']} "
            f"| {r.get('verdict','')} | {bmm} | {r.get('model_attributed',0)} | {dod} "
            f"| {report_cell} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


def cmd_render(args) -> None:
    out = md_path(args.ledger)
    with open(out, "w", encoding="utf-8") as f:
        f.write(render(args.ledger))
    print(f"wrote {out}")


def cmd_record(args) -> None:
    if args.verdict not in VERDICTS:
        sys.exit(f"verdict must be one of {VERDICTS}")
    if args.phase not in PHASES:
        sys.exit(f"phase must be one of {PHASES}")
    if bool(args.adr) == bool(args.issue):
        sys.exit("give exactly one of --adr or --issue")
    if (args.phase == "fix") != bool(args.issue):
        sys.exit("--issue goes with --phase fix, --adr with the other phases")
    if args.model_attributed > (args.blockers + args.majors + args.minors):
        sys.exit("--model-attributed cannot exceed total findings (blockers+majors+minors)")
    if args.dod_total and args.dod_passed > args.dod_total:
        sys.exit("--dod-passed cannot exceed --dod-total")

    records = load(args.ledger)
    records.append({
        "date": args.date or dt.date.today().isoformat(),
        **({"issue": args.issue} if args.issue else {"adr": args.adr}),
        "phase": args.phase,
        "model": args.model,
        "verdict": args.verdict,
        "blockers": args.blockers,
        "majors": args.majors,
        "minors": args.minors,
        "model_attributed": args.model_attributed,
        "dod_passed": args.dod_passed,
        "dod_total": args.dod_total,
        "report": args.report,
        "notes": args.notes,
    })
    os.makedirs(os.path.dirname(args.ledger) or ".", exist_ok=True)
    with open(args.ledger, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)
        f.write("\n")
    cmd_render(args)
    what = issue_ref(args.issue) if args.issue else f"ADR-{args.adr}"
    print(f"recorded review: {args.model} on {what} ({args.phase}) → {args.verdict}")


def main() -> None:
    p = argparse.ArgumentParser(description="ADR implementation model-quality ledger")
    sub = p.add_subparsers(dest="cmd", required=True)

    rec = sub.add_parser("record", help="append a review record + regenerate the scorecard")
    rec.add_argument("--ledger", required=True)
    rec.add_argument("--adr", default="", help="ADR number, e.g. 0001")
    rec.add_argument("--issue", default="", help="issue of a fix review, e.g. 24, or funcd-python#30 for a language repo (with --phase fix)")
    rec.add_argument("--phase", required=True, help=f"one of {PHASES}")
    rec.add_argument("--model", required=True, help="model that produced the work, e.g. sonnet-4.6")
    rec.add_argument("--verdict", required=True, help=f"one of {VERDICTS}")
    rec.add_argument("--blockers", type=int, default=0)
    rec.add_argument("--majors", type=int, default=0)
    rec.add_argument("--minors", type=int, default=0)
    rec.add_argument("--model-attributed", type=int, default=0,
                     help="of the findings above, how many are the MODEL's fault (rest = ADR/env)")
    rec.add_argument("--dod-passed", type=int, default=0)
    rec.add_argument("--dod-total", type=int, default=0)
    rec.add_argument("--report", default="",
                     help="repo-relative path to the full verdict doc, e.g. "
                          "docs/reviews/adr-0001-scaffold-<model>.md (linked from the scorecard)")
    rec.add_argument("--notes", default="")
    rec.add_argument("--date", default="", help="override date (default: today)")
    rec.set_defaults(func=cmd_record)

    ren = sub.add_parser("render", help="regenerate the markdown scorecard from the ledger")
    ren.add_argument("--ledger", required=True)
    ren.set_defaults(func=cmd_render)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
