package controlplane_test

import (
	"encoding/json"
	"net/http"
	"os"
	"strings"
	"testing"

	"github.com/danielgtaylor/huma/v2/humatest"
	"github.com/go-chi/chi/v5"

	"github.com/pyvvo/funcd/api/fault"
	v1 "github.com/pyvvo/funcd/api/types/v1alpha1"
	"github.com/pyvvo/funcd/internal/controlplane"
)

// ===== helpers =====

func makeFunction(ns, name string) map[string]interface{} {
	return map[string]interface{}{
		"apiVersion": "funcd.io/v1alpha1",
		"kind":       "Function",
		"metadata": map[string]interface{}{
			"name":      name,
			"namespace": ns,
		},
		"spec": map[string]interface{}{},
	}
}

// ===== scenario: typed-operation-roundtrip =====

func TestTypedOperationRoundtrip(t *testing.T) {
	h := controlplane.NewStubHandlers()
	r := chi.NewRouter()
	api := controlplane.NewAPI(r, h)
	ta := humatest.Wrap(t, api)

	input := makeFunction("my-ns", "my-fn")
	createResp := ta.Post("/apis/funcd.io/v1alpha1/namespaces/my-ns/functions",
		"Accept: application/json", input)
	if createResp.Code != http.StatusOK && createResp.Code != http.StatusCreated {
		t.Fatalf("expected 200 OK or 201 Created, got %d: %s", createResp.Code, createResp.Body.String())
	}

	// GET the created function
	getResp := ta.Get("/apis/funcd.io/v1alpha1/namespaces/my-ns/functions/my-fn",
		"Accept: application/json")
	if getResp.Code != http.StatusOK {
		t.Fatalf("expected 200 OK, got %d: %s", getResp.Code, getResp.Body.String())
	}

	// Decode directly into v1.Function — huma serializes the Body field as the response body.
	var fn v1.Function
	if err := json.Unmarshal(getResp.Body.Bytes(), &fn); err != nil {
		t.Fatalf("failed to decode response: %v", err)
	}
	if fn.Name != "my-fn" || fn.Namespace != "my-ns" {
		t.Errorf("round-trip mismatch: name=%s ns=%s", fn.Name, fn.Namespace)
	}
}

// ===== scenario: error-is-problem-json =====

func TestErrorIsProblemJSON(t *testing.T) {
	h := controlplane.NewStubHandlers()
	r := chi.NewRouter()
	api := controlplane.NewAPI(r, h)
	ta := humatest.Wrap(t, api)

	resp := ta.Get("/apis/funcd.io/v1alpha1/namespaces/no-ns/functions/no-fn",
		"Accept: application/json")
	if resp.Code != http.StatusNotFound {
		t.Fatalf("expected 404, got %d", resp.Code)
	}

	if ct := resp.Header().Get("Content-Type"); ct != "application/problem+json" {
		t.Errorf("expected application/problem+json, got %q", ct)
	}

	// Decode the response body as a Problem (RFC 9457 shape).
	var raw map[string]interface{}
	if err := json.Unmarshal(resp.Body.Bytes(), &raw); err != nil {
		t.Fatalf("failed to decode problem+json: %v", err)
	}
	status, ok := raw["status"].(float64)
	if !ok {
		t.Fatalf("expected numeric status in problem+json, got %T: %v", raw["status"], raw["status"])
	}
	if int(status) != http.StatusNotFound {
		t.Errorf("expected status 404, got %d", int(status))
	}
	// Verify it's problem+json — should have "type", "title", "status", "detail".
	for _, field := range []string{"type", "title", "detail"} {
		if _, exists := raw[field]; !exists {
			t.Errorf("expected problem+json field %q, not found in response", field)
		}
	}
}

// ===== scenario: openapi-doc-served =====

func TestOpenAPIDocServed(t *testing.T) {
	h := controlplane.NewStubHandlers()
	r := chi.NewRouter()
	api := controlplane.NewAPI(r, h)
	ta := humatest.Wrap(t, api)

	resp := ta.Get("/openapi.yaml", "Accept: application/yaml")
	if resp.Code != http.StatusOK {
		t.Fatalf("expected 200 OK for /openapi.yaml, got %d", resp.Code)
	}
	body := resp.Body.String()
	if body == "" {
		t.Fatal("expected non-empty OpenAPI spec")
	}
	if !strings.Contains(body, "openapi: 3.1.") && !strings.Contains(body, "openapi: \"3.1") {
		t.Errorf("expected OpenAPI 3.1, got first 200 chars:\n%s", body[:minint(200, len(body))])
	}
}

// ===== scenario: spec-generated-from-go =====

func TestSpecGeneratedFromGo(t *testing.T) {
	_ = fault.Problem{} // use fault import

	h := controlplane.NewStubHandlers()
	r := chi.NewRouter()
	api := controlplane.NewAPI(r, h)
	controlplane.RegisterStubLogs(api)            // ADR-0084: the logs route is part of the committed spec
	controlplane.RegisterStubWorkflowRunLogs(api) // ADR-0106: the run-scoped logs route is part of the committed spec
	controlplane.RegisterStubDeadLetters(api)     // ADR-0118: the DLQ read + replay/discard routes are part of the committed spec

	raw, err := api.OpenAPI().YAML()
	if err != nil {
		t.Fatalf("failed to generate YAML: %v", err)
	}

	committed, err := os.ReadFile("../../api/openapi/funcd.v1alpha1.yaml")
	if err != nil {
		t.Skipf("committed spec not found: %v", err)
		return
	}

	// Strip the specgen header from the committed spec for comparison.
	committedStr := string(committed)
	committedStr = strings.TrimPrefix(committedStr, "# Generated by funcd specgen — DO NOT EDIT.\n")
	committedStr = strings.TrimPrefix(committedStr, "# This file is derived from typed Go operations and committed for CI staleness checking.\n")
	committedStr = strings.TrimPrefix(committedStr, "\n")

	generated := string(raw)
	if generated != committedStr {
		t.Errorf("generated spec differs from committed spec.\nGenerated: %d bytes, Committed: %d bytes\nFirst diff at byte %d\nGenerated prefix:\n%s\n\nCommitted prefix:\n%s",
			len(generated), len(committedStr),
			firstDiff(generated, committedStr),
			trunc(generated, 300),
			trunc(committedStr, 300))
	}
}

// ===== scenario: spec-reflects-go-shape =====

func TestSpecReflectsGoShape(t *testing.T) {
	h := controlplane.NewStubHandlers()
	r := chi.NewRouter()
	api := controlplane.NewAPI(r, h)

	raw, err := api.OpenAPI().YAML()
	if err != nil {
		t.Fatalf("failed to generate YAML: %v", err)
	}

	spec := string(raw)
	for _, word := range []string{"Function", "ObjectMeta", "Namespace"} {
		if !strings.Contains(spec, word) {
			t.Errorf("expected %q in generated spec", word)
		}
	}
}

// ===== helpers =====

func minint(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func trunc(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

func firstDiff(a, b string) int {
	n := minint(len(a), len(b))
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return i
		}
	}
	if len(a) != len(b) {
		return n
	}
	return -1
}

// ===== scenario: schema-rejects-invalid-dto =====
// huma validates the request body against the generated schema BEFORE the handler runs:
// the DNS-1123 name pattern (ObjectName SchemaProvider) and replicas>=0 (struct tag) are
// enforced at the edge, returning 422 — proving both validation mechanisms are wired.
func TestSchemaRejectsInvalidDTO(t *testing.T) {
	h := controlplane.NewStubHandlers()
	r := chi.NewRouter()
	api := controlplane.NewAPI(r, h)
	ta := humatest.Wrap(t, api)
	const path = "/apis/funcd.io/v1alpha1/namespaces/my-ns/functions"

	badName := map[string]interface{}{
		"metadata": map[string]interface{}{"name": "Bad_Name!", "namespace": "my-ns", "resourceGroup": "rg1"},
		"spec":     map[string]interface{}{"runtime": "nodejs22"},
	}
	if resp := ta.Post(path, "Content-Type: application/json", badName); resp.Code != http.StatusUnprocessableEntity {
		t.Fatalf("bad DNS-1123 name: want 422 (schema pattern), got %d: %s", resp.Code, resp.Body.String())
	}

	negReplicas := map[string]interface{}{
		"metadata": map[string]interface{}{"name": "ok-name", "namespace": "my-ns", "resourceGroup": "rg1"},
		"spec":     map[string]interface{}{"runtime": "nodejs22", "replicas": -1},
	}
	if resp := ta.Post(path, "Content-Type: application/json", negReplicas); resp.Code != http.StatusUnprocessableEntity {
		t.Fatalf("negative replicas: want 422 (schema minimum:0), got %d: %s", resp.Code, resp.Body.String())
	}

	overCap := map[string]interface{}{
		"metadata": map[string]interface{}{"name": "ok-name", "namespace": "my-ns", "resourceGroup": "rg1"},
		"spec":     map[string]interface{}{"runtime": "nodejs22", "replicas": 16},
	}
	if resp := ta.Post(path, "Content-Type: application/json", overCap); resp.Code != http.StatusUnprocessableEntity {
		t.Fatalf("replicas over cap: want 422 (schema maximum:15), got %d: %s", resp.Code, resp.Body.String())
	}

	// new schema leaves: a bad runtime (RuntimeName DNS-1123) and a bad handler (handlerPattern).
	for _, bad := range []struct {
		what string
		spec map[string]interface{}
	}{
		{"runtime", map[string]interface{}{"runtime": "Bad_Runtime!", "handler": "h"}},
		{"handler", map[string]interface{}{"runtime": "nodejs22", "handler": "1-bad-handler"}},
	} {
		body := map[string]interface{}{
			"metadata": map[string]interface{}{"name": "ok-name", "namespace": "my-ns", "resourceGroup": "rg1"},
			"spec":     bad.spec,
		}
		if resp := ta.Post(path, "Content-Type: application/json", body); resp.Code != http.StatusUnprocessableEntity {
			t.Fatalf("bad %s: want 422 (schema), got %d: %s", bad.what, resp.Code, resp.Body.String())
		}
	}
}

// ===== scenario: site-requires-ingress (ADR-0139) =====
// A Site's ingress is required in V1: the generated schema marks it required, so a body without it is
// rejected at the edge (422) before any handler runs; the same body with an ingress is created (201).
// Validate() cannot see the absence of a value-typed field, so the wire schema is the enforcement path.
func TestScenarioSiteSchemaRequiresIngress(t *testing.T) {
	h := controlplane.NewStubHandlers()
	r := chi.NewRouter()
	api := controlplane.NewAPI(r, h)
	ta := humatest.Wrap(t, api)
	const path = "/apis/funcd.io/v1alpha1/namespaces/my-ns/sites"

	spec := map[string]interface{}{
		"image":  "oci-layout:///layout:bi",
		"bucket": map[string]interface{}{"name": "reports"},
		"prefix": "bi",
	}
	body := map[string]interface{}{
		"apiVersion": "funcd.io/v1alpha1",
		"kind":       "Site",
		"metadata":   map[string]interface{}{"name": "bi", "namespace": "my-ns", "resourceGroup": "rg1"},
		"spec":       spec,
	}
	if resp := ta.Post(path, "Content-Type: application/json", body); resp.Code != http.StatusUnprocessableEntity {
		t.Fatalf("missing spec.ingress: want 422 (schema required), got %d: %s", resp.Code, resp.Body.String())
	}
	spec["ingress"] = map[string]interface{}{"host": "bi.example.com"}
	if resp := ta.Post(path, "Content-Type: application/json", body); resp.Code != http.StatusOK && resp.Code != http.StatusCreated {
		t.Fatalf("with spec.ingress: want 2xx, got %d: %s", resp.Code, resp.Body.String())
	}
}

// ===== scenario: control-plane-body-over-cap (ADR-0148) =====
// A body over huma's 1 MiB MaxBodyBytes answers funcd's PayloadTooLarge problem, not huma's about:blank.
func TestScenarioControlPlaneBodyOverCap(t *testing.T) {
	ta := humatest.Wrap(t, controlplane.NewAPI(chi.NewRouter(), controlplane.NewStubHandlers()))
	body := strings.NewReader(`{"metadata":{"name":"` + strings.Repeat("x", 1<<20) + `"}}`)
	resp := ta.Post("/apis/funcd.io/v1alpha1/namespaces/my-ns/functions", "Content-Type: application/json", body)
	if resp.Code != http.StatusRequestEntityTooLarge {
		t.Fatalf("want 413, got %d: %.300s", resp.Code, resp.Body.String())
	}
	if ct := resp.Header().Get("Content-Type"); ct != "application/problem+json" {
		t.Errorf("want application/problem+json, got %q", ct)
	}
	var p fault.Problem
	if err := json.Unmarshal(resp.Body.Bytes(), &p); err != nil {
		t.Fatalf("decode problem: %v", err)
	}
	if p.Type != "urn:funcd:problem:payload-too-large" || p.Title != "Content Too Large" || p.Status != http.StatusRequestEntityTooLarge {
		t.Fatalf("want funcd's payload-too-large problem, got %+v", p)
	}
}
