#!/usr/bin/env python3
"""Driver for funcd's GitHub issues (repo pyvvo/funcd).

The issue shapes (SHAPES) and the label taxonomy (LABELS) are defined once, below, and everything
else derives from them: the issue forms in .github/ISSUE_TEMPLATE (`forms` writes them, `forms --check`
fails on drift), the repo's labels (`labels --sync`), and the checks `create` runs before it files an
issue. Shells out to the `gh` CLI (system PATH) + python3 only; the Nix dev shell is not required.

  driver.py list [--state open|closed|all] [--label L]    # issues: #n state [labels] title
  driver.py show <number> [--body]                        # one issue: title, labels, url, body (--body: body only)
  driver.py template <kind>                               # an empty body in the kind's shape
  driver.py create --kind K --title T --area A [--area A]... --priority P [--needs-adr]
                   --body-file F|- [--dry-run]            # check, then file the issue
  driver.py edit <number> [--title T] [--body-file F|-]   # check against the issue's kind, then update it
  driver.py relabel <number> [--add L]... [--remove L]...
  driver.py labels [--sync]                               # the taxonomy vs the repo; --sync fixes it
  driver.py forms [--check]                               # write the issue forms; --check fails on drift
"""
import argparse
import json
import re
import subprocess
import sys
from collections import namedtuple
from pathlib import Path

REPO = "pyvvo/funcd"
ROOT = Path(__file__).resolve().parents[3]
FORMS_DIR = ROOT / ".github" / "ISSUE_TEMPLATE"
GENERATED = "# Generated by .claude/skills/issue-management/driver.py forms. Edit the driver, not this file."

# --- the label taxonomy: one kind/ and one priority/ per issue, one or more area/ -----------------
LABELS = {
    "kind/bug": ("d73a4a", "The platform does something wrong"),
    "kind/feature": ("a2eeef", "A new capability"),
    "kind/flake": ("f9d0c4", "A test that fails intermittently"),
    "kind/task": ("c5def5", "Docs, tooling, CI or cleanup work"),
    "area/function": ("1d76db", "Function and Revision lifecycle: deploy, scaling, pooling, I/O contract, artifacts"),
    "area/runtime": ("1d76db", "Worker drivers (process, containerd), runtime shims and images, isolation"),
    "area/control-plane": ("1d76db", "API server, admission, controller engine, store"),
    "area/data-plane": ("1d76db", "Invoke path: gateway, edge router, activator, routes"),
    "area/services": ("1d76db", "Platform services and their providers: blob, KV, catalog, site, config"),
    "area/eventing": ("1d76db", "Bus, event sources, sensors, workflows"),
    "area/security": ("1d76db", "Authentication, authorization policies, secrets, egress"),
    "area/observability": ("1d76db", "Logs, traces, metrics"),
    "area/cli": ("1d76db", "funcdctl and the SDK"),
    "area/ci": ("1d76db", "CI, release, build tooling, e2e lanes, test infrastructure"),
    "area/docs": ("1d76db", "Blueprint, feat docs, ADRs, roadmap, skills"),
    "priority/critical": ("b60205", "Security hole, data loss, or the platform down"),
    "priority/high": ("d93f0b", "A core path is broken, with no good workaround"),
    "priority/medium": ("fbca04", "Wrong behavior, with a workaround"),
    "priority/low": ("0e8a16", "Minor or cosmetic"),
    "needs-adr": ("5319e7", "The fix needs a design decision (an ADR) before code"),
    "needs-triage": ("ededed", "Not yet labeled by a maintainer"),
}
# GitHub's default labels that this taxonomy replaces; `labels --sync` renames them.
RENAMES = {"bug": "kind/bug", "enhancement": "kind/feature", "documentation": "area/docs"}

# --- the issue shapes: one form per kind; the field order is the body's section order -------------
Field = namedtuple("Field", "id label hint required")
Shape = namedtuple("Shape", "name about fields")
REFERENCES = Field("references", "References", "Related ADRs, issues, PRs or board cards.", False)
SHAPES = {
    "bug": Shape("Bug report", "The platform does something wrong.", [
        Field("summary", "Summary", "What is wrong, in one or two sentences.", True),
        Field("reproduce", "Steps to reproduce", "The exact commands, manifests or test that show it.", True),
        Field("expected", "Expected behavior", "What should happen, as observable behavior.", True),
        Field("actual", "Actual behavior", "What happens instead, with the output: logs, status, errors.", True),
        Field("environment", "Environment", "funcd version or commit, runtime driver (process or containerd), OS.", True),
        Field("cause", "Root cause", "If known: the code (file:line) and the ADRs it touches.", False),
        Field("workaround", "Workaround", "How to get by until it is fixed, and whether it was tested.", False),
        REFERENCES,
    ]),
    "feature": Shape("Feature request", "A capability funcd does not have yet.", [
        Field("summary", "Summary", "The capability, in one or two sentences.", True),
        Field("problem", "Problem", "Who needs it and why, and what they do today.", True),
        Field("behavior", "Proposed behavior", "What it should do, as observable behavior, not how to build it.", True),
        Field("alternatives", "Alternatives", "Other ways to solve it, and why they fall short.", False),
        REFERENCES,
    ]),
    "flake": Shape("Flaky test", "A test that fails intermittently.", [
        Field("test", "Test", "The package and the test name.", True),
        Field("failure", "Failure", "The failing assertion or error output.", True),
        Field("frequency", "Frequency", "How often it fails, and where: local runs or a CI run link.", True),
        Field("cause", "Suspected cause", "If known: what races, or what depends on timing or order.", False),
        REFERENCES,
    ]),
    "task": Shape("Task", "Docs, tooling, CI or cleanup work.", [
        Field("summary", "Summary", "The work, in one or two sentences.", True),
        Field("details", "Details", "What to change and why.", True),
        Field("done", "Done when", "The checkable result that closes the issue.", True),
        REFERENCES,
    ]),
}
NO_RESPONSE = "_No response_"  # what GitHub writes for an optional form field left empty
LOCAL_PATH = re.compile(r"/Users/|/home/|/private/|/var/folders/|[A-Za-z]:\\Users\\")


def gh(*args, stdin=None):
    """Run a gh command; exit with its stderr on failure."""
    r = subprocess.run(["gh", *args], capture_output=True, text=True, input=stdin)
    if r.returncode != 0:
        sys.exit(f"error: gh {' '.join(args)}\n{r.stderr.strip()}")
    return r.stdout


def live_labels():
    out = gh("label", "list", "-R", REPO, "--limit", "200", "--json", "name,color,description")
    return {lb["name"]: lb for lb in json.loads(out)}


def issues(state="open", label=None):
    args = ["issue", "list", "-R", REPO, "--state", state, "--limit", "200", "--json", "number,title,state,labels"]
    if label:
        args += ["--label", label]
    return json.loads(gh(*args))


def names(labels):
    return " ".join(sorted(lb["name"] for lb in labels))


def placeholder(f):
    return f"<{f.hint}>" if f.required else f"<optional: {f.hint}>"


def sections(body):
    """Split a body into (heading, content) pairs at `### ` lines outside code fences."""
    out, fenced = [], False
    for line in body.splitlines():
        if line.lstrip().startswith("```"):
            fenced = not fenced
        if not fenced and line.startswith("### "):
            out.append((line[4:].strip(), []))
        elif out:
            out[-1][1].append(line)
        elif line.strip():
            sys.exit("error: the body has text before its first section")
    return [(heading, "\n".join(lines).strip()) for heading, lines in out]


def check_body(kind, body):
    """Return the body normalized to the kind's shape, or exit naming every problem."""
    fields = SHAPES[kind].fields
    got = sections(body)
    want = [f.label for f in fields]
    if [heading for heading, _ in got] != want:
        sys.exit("error: the sections must be, in this order:\n  " + "\n  ".join(want)
                 + "\ngot:\n  " + "\n  ".join(heading for heading, _ in got))
    problems, parts = [], []
    for f, (_, text) in zip(fields, got):
        empty = text in ("", NO_RESPONSE, placeholder(f))
        if empty and f.required:
            problems.append(f"{f.label} is required")
        parts.append(f"### {f.label}\n\n{NO_RESPONSE if empty else text}")
    m = LOCAL_PATH.search(body)
    if m:
        problems.append(f"a local absolute path ({m.group(0)}...): write project-root-relative paths")
    if problems:
        sys.exit("error: " + "; ".join(problems))
    return "\n\n".join(parts) + "\n"


def check_title(title):
    if not title or len(title) > 80 or title.endswith(".") or re.match(r"\[|[a-z]+(\([^)]*\))?: ", title):
        sys.exit("error: a title is a plain sentence of at most 80 characters, with no trailing period "
                 "and no [tag] or type: prefix (the labels carry the kind)")


def taxonomy(prefix, value):
    name = value if value.startswith(prefix) else prefix + value
    if name not in LABELS:
        choices = ", ".join(n[len(prefix):] for n in LABELS if n.startswith(prefix))
        sys.exit(f"error: unknown label {name}; choose from: {choices}")
    return name


def cmd_list(a):
    for it in issues(a.state, a.label):
        print(f"#{it['number']} {it['state']} [{names(it['labels'])}] {it['title']}")


def cmd_show(a):
    it = json.loads(gh("issue", "view", str(a.number), "-R", REPO, "--json", "number,title,state,labels,url,body"))
    if a.body:
        print(it["body"])
        return
    print(f"#{it['number']} {it['state']} [{names(it['labels'])}] {it['title']}\n{it['url']}\n\n{it['body']}")


def cmd_template(a):
    print("\n\n".join(f"### {f.label}\n\n{placeholder(f)}" for f in SHAPES[a.kind].fields))


def cmd_create(a):
    check_title(a.title)
    labels = [f"kind/{a.kind}"] + [taxonomy("area/", x) for x in a.area] + [taxonomy("priority/", a.priority)]
    if a.needs_adr:
        labels.append("needs-adr")
    body = check_body(a.kind, sys.stdin.read() if a.body_file == "-" else Path(a.body_file).read_text())
    if a.dry_run:
        print(f"title:  {a.title}\nlabels: {' '.join(labels)}\n\n{body}")
        return
    missing = [lb for lb in labels if lb not in live_labels()]
    if missing:
        sys.exit(f"error: {REPO} lacks the labels {', '.join(missing)}; run `driver.py labels --sync`")
    dup = [it for it in issues() if it["title"].lower() == a.title.lower()]
    if dup:
        sys.exit(f"error: open issue #{dup[0]['number']} already has this title")
    args = ["issue", "create", "-R", REPO, "--title", a.title, "--body-file", "-"]
    for lb in labels:
        args += ["--label", lb]
    print(gh(*args, stdin=body).strip())


def cmd_edit(a):
    if not a.title and not a.body_file:
        sys.exit("error: nothing to edit; pass --title and/or --body-file")
    labels = json.loads(gh("issue", "view", str(a.number), "-R", REPO, "--json", "labels"))["labels"]
    kinds = [lb["name"][len("kind/"):] for lb in labels if lb["name"].startswith("kind/")]
    if len(kinds) != 1 or kinds[0] not in SHAPES:
        sys.exit(f"error: #{a.number} needs exactly one known kind/ label to check against; relabel it first")
    args, body = ["issue", "edit", str(a.number), "-R", REPO], None
    if a.title:
        check_title(a.title)
        args += ["--title", a.title]
    if a.body_file:
        body = check_body(kinds[0], sys.stdin.read() if a.body_file == "-" else Path(a.body_file).read_text())
        args += ["--body-file", "-"]
    gh(*args, stdin=body)
    print(f"#{a.number} updated")


def cmd_relabel(a):
    cur = {lb["name"] for lb in json.loads(gh("issue", "view", str(a.number), "-R", REPO, "--json", "labels"))["labels"]}
    unknown = [lb for lb in a.add if lb not in live_labels()]
    if unknown:
        sys.exit(f"error: {REPO} has no label {', '.join(unknown)}")
    new = (cur - set(a.remove)) | set(a.add)
    for prefix in ("kind/", "priority/"):
        if sum(lb.startswith(prefix) for lb in new) > 1:
            sys.exit(f"error: an issue carries at most one {prefix} label")
    args = ["issue", "edit", str(a.number), "-R", REPO]
    for lb in a.add:
        args += ["--add-label", lb]
    for lb in a.remove:
        args += ["--remove-label", lb]
    gh(*args)
    print(f"#{a.number} [{' '.join(sorted(new))}]")


def cmd_labels(a):
    live = live_labels()
    drift = False
    for old, new in RENAMES.items():
        if old in live and new not in live:
            drift = True
            print(f"rename   {old} -> {new}")
            if a.sync:
                color, desc = LABELS[new]
                gh("label", "edit", old, "-R", REPO, "--name", new, "--color", color, "--description", desc)
    if a.sync:
        live = live_labels()
    for name, (color, desc) in LABELS.items():
        cur = live.get(name)
        state = "missing" if cur is None else "ok" if (cur["color"].lower(), cur["description"]) == (color, desc) else "differs"
        print(f"{state:8} {name}")
        if state != "ok":
            drift = True
            if a.sync:
                gh("label", "create", name, "-R", REPO, "--color", color, "--description", desc, "--force")
    other = sorted(set(live) - set(LABELS))
    if other:
        print("kept     " + ", ".join(other))
    if drift and not a.sync:
        sys.exit("DRIFT: run `driver.py labels --sync`")


def scalar(s):
    """A YAML scalar: plain when that is unambiguous, else double-quoted (JSON strings are valid YAML)."""
    return s if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9 ,.()/_-]*", s) else json.dumps(s)


def form(kind):
    shape = SHAPES[kind]
    lines = [GENERATED, f"name: {scalar(shape.name)}", f"description: {scalar(shape.about)}",
             "labels:", f"  - kind/{kind}", "  - needs-triage", "body:"]
    for f in shape.fields:
        lines += ["  - type: textarea", f"    id: {f.id}", "    attributes:", f"      label: {scalar(f.label)}",
                  f"      description: {scalar(f.hint)}", "    validations:", f"      required: {str(f.required).lower()}"]
    return "\n".join(lines) + "\n"


def cmd_forms(a):
    want = {f"{kind}.yml": form(kind) for kind in SHAPES}
    want["config.yml"] = f"{GENERATED}\nblank_issues_enabled: false\n"
    have = {p.name: p.read_text() for p in FORMS_DIR.glob("*.yml")}
    stale = sorted(n for n, text in have.items() if n not in want and text.startswith(GENERATED))
    drift = sorted(n for n in want if have.get(n) != want[n]) + stale
    if a.check:
        if drift:
            sys.exit(f"error: issue forms out of date: {', '.join(drift)}; run `driver.py forms`")
        print("issue forms match the driver")
        return
    FORMS_DIR.mkdir(parents=True, exist_ok=True)
    for n, text in want.items():
        (FORMS_DIR / n).write_text(text)
    for n in stale:
        (FORMS_DIR / n).unlink()
    print(f"wrote {', '.join(sorted(want))}" + (f"; removed {', '.join(stale)}" if stale else ""))


def main():
    p = argparse.ArgumentParser(description="funcd GitHub issues driver")
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("list")
    s.add_argument("--state", default="open", choices=["open", "closed", "all"])
    s.add_argument("--label")
    s = sub.add_parser("show")
    s.add_argument("number", type=int)
    s.add_argument("--body", action="store_true")
    s = sub.add_parser("template")
    s.add_argument("kind", choices=list(SHAPES))
    s = sub.add_parser("create")
    s.add_argument("--kind", required=True, choices=list(SHAPES))
    s.add_argument("--title", required=True)
    s.add_argument("--area", action="append", required=True)
    s.add_argument("--priority", required=True)
    s.add_argument("--needs-adr", action="store_true")
    s.add_argument("--body-file", required=True, help="a file, or - for stdin")
    s.add_argument("--dry-run", action="store_true")
    s = sub.add_parser("edit")
    s.add_argument("number", type=int)
    s.add_argument("--title")
    s.add_argument("--body-file", help="a file, or - for stdin")
    s = sub.add_parser("relabel")
    s.add_argument("number", type=int)
    s.add_argument("--add", action="append", default=[])
    s.add_argument("--remove", action="append", default=[])
    s = sub.add_parser("labels")
    s.add_argument("--sync", action="store_true")
    s = sub.add_parser("forms")
    s.add_argument("--check", action="store_true")
    a = p.parse_args()
    {"list": cmd_list, "show": cmd_show, "template": cmd_template, "create": cmd_create,
     "edit": cmd_edit, "relabel": cmd_relabel, "labels": cmd_labels, "forms": cmd_forms}[a.cmd](a)


if __name__ == "__main__":
    main()
