// Command specgen writes the huma-generated OpenAPI 3.1 spec to the committed path.
// It builds the API with stub handlers and writes the YAML output deterministically.
// Usage: go run ./cmd/specgen/ -out ../../api/openapi/funcd.v1alpha1.yaml
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/go-chi/chi/v5"

	"github.com/green-0-rabbit/funcd/internal/controlplane"
)

func main() {
	outPath := flag.String("out", "api/openapi/funcd.v1alpha1.yaml", "output path for the OpenAPI YAML spec")
	flag.Parse()

	r := chi.NewRouter()
	h := controlplane.NewStubHandlers()
	api := controlplane.NewAPI(r, h)
	controlplane.RegisterStubLogs(api)            // ADR-0084: document the function-logs route in the committed spec
	controlplane.RegisterStubWorkflowRunLogs(api) // ADR-0106: document the run-scoped logs route in the committed spec

	raw, yamlErr := api.OpenAPI().YAML()
	if yamlErr != nil {
		fmt.Fprintf(os.Stderr, "specgen: failed to generate YAML: %v\n", yamlErr)
		os.Exit(1)
	}

	// Canonicalize: sort keys for deterministic output.
	canonical := string(raw)
	if !strings.HasPrefix(canonical, "# Generated by funcd specgen") {
		canonical = "# Generated by funcd specgen — DO NOT EDIT.\n# This file is derived from typed Go operations and committed for CI staleness checking.\n\n" + canonical
	}

	// Sort map keys deterministically.
	canonical = canonicalizeYAML(canonical)

	if err := os.WriteFile(*outPath, []byte(canonical), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "specgen: failed to write spec: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "specgen: wrote %s\n", *outPath)
}

// canonicalizeYAML reorders top-level map keys for deterministic output.
// huma's YAML emitter uses Go maps which have non-deterministic iteration order.
func canonicalizeYAML(raw string) string {
	lines := strings.Split(raw, "\n")

	// Prepend header if missing.
	if !strings.HasPrefix(raw, "# Generated by funcd specgen") {
		lines = append([]string{
			"# Generated by funcd specgen — DO NOT EDIT.",
			"# This file is derived from typed Go operations and committed for CI staleness checking.",
			"",
		}, lines...)
	}

	// Sort the 'paths' entries if they exist.
	result := strings.Join(lines, "\n")
	result = sortPathsSection(result)
	return result
}

// sortPathsSection sorts paths within the OpenAPI 'paths:' block alphabetically.
func sortPathsSection(raw string) string {
	// Find the 'paths:' section and sort its entries.
	// This is a simple line-based sort that handles the common huma output format.
	idx := strings.Index(raw, "\npaths:\n")
	if idx < 0 {
		return raw
	}

	// Collect path entries until next top-level key or end.
	rest := raw[idx+len("\npaths:\n"):]
	var entries []string
	current := ""
	depth := 0
	for _, line := range strings.Split(rest, "\n") {
		if depth == 0 && (line == "" || (len(line) > 0 && line[0] != ' ' && line[0] != '\t')) {
			// We hit a top-level key or empty line — flush current entry.
			if current != "" {
				entries = append(entries, strings.TrimRight(current, "\n"))
			}
			if line == "" {
				continue
			}
			// This is the next top-level key — we're done with paths.
			current = ""
			break
		}
		if depth == 0 && len(line) > 0 && (line[0] == ' ' || line[0] == '\t') {
			current += line + "\n"
			// Count leading spaces for depth.
			leading := 0
			for _, c := range line {
				if c == ' ' {
					leading++
				} else {
					break
				}
			}
			depth = leading
		} else if depth > 0 && len(line) > 0 && strings.HasPrefix(line, strings.Repeat(" ", depth)) {
			current += line + "\n"
		} else if line == "" && current != "" {
			current += line + "\n"
		} else {
			if current != "" {
				entries = append(entries, strings.TrimRight(current, "\n"))
			}
			current = ""
			depth = 0
			if line != "" {
				current = line + "\n"
				depth = 0
			}
		}
	}
	if current != "" {
		entries = append(entries, strings.TrimRight(current, "\n"))
	}

	if len(entries) <= 1 {
		return raw
	}

	sort.Slice(entries, func(i, j int) bool {
		// Extract the path key (first non-empty line, trim leading /{path}).
		pi := strings.TrimSpace(strings.SplitN(entries[i], "\n", 2)[0])
		pj := strings.TrimSpace(strings.SplitN(entries[j], "\n", 2)[0])
		return pi < pj
	})

	sorted := raw[:idx] + "\npaths:\n"
	for _, e := range entries {
		sorted += e + "\n"
	}
	// Append remaining content after paths.
	afterPaths := rest
	for _, e := range entries {
		afterPaths = strings.Replace(afterPaths, e+"\n", "", 1)
	}
	sorted += afterPaths
	return sorted
}
