package sdk

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/pyvvo/funcd/api/fault"
	"github.com/pyvvo/funcd/internal/contract"
)

// Filenames for the generated declaration files, keyed by runtime family.
const (
	// A real .py module (not a .pyi stub) so a python handler imports it at the TOP LEVEL — no
	// `if TYPE_CHECKING:` dance (a .pyi is not runtime-importable). The generated TypedDicts are
	// lightweight and the handler uses them only in (lazy) annotations, so the import is cheap.
	pyFileName  = "funcd_types.py"
	dtsFileName = "funcd.d.ts"
)

// GenerateTypes emits editor-facing declaration files from a manifest (ADR-0122 Decision 4): the
// FuncInput/FuncOutput payload types (from the contract JSON Schema) plus a typed binding context (from
// the declared aliases). python314 ⇒ a ".py" module (top-level-importable, no TYPE_CHECKING dance);
// nodejs22 ⇒ a ".d.ts" (imported with `import type`). This is DX-only — the platform never trusts these
// types; they exist to give the author editor autocomplete over the bounded funcd profile. The map is
// keyed by the file's basename; the caller writes each into the output directory.
func GenerateTypes(m *Manifest) (map[string][]byte, error) {
	const op = "sdk.GenerateTypes"
	input, output, err := m.ContractSides()
	if err != nil {
		return nil, err
	}
	in, ierr := parseTypeSchema(input)
	if ierr != nil {
		return nil, fault.Wrapf(ierr, fault.Invalid, op, "input contract is not a usable JSON Schema")
	}
	out, oerr := parseTypeSchema(output)
	if oerr != nil {
		return nil, fault.Wrapf(oerr, fault.Invalid, op, "output contract is not a usable JSON Schema")
	}
	family := runtimeFamily(string(m.Runtime))
	switch family {
	case "python":
		return map[string][]byte{pyFileName: genPyi(in, out, m.Bindings)}, nil
	case "node":
		return map[string][]byte{dtsFileName: genDts(in, out, m.Bindings)}, nil
	default:
		return nil, fault.Invalidf(op, "runtime %q has no type-generation target (expected a python* or node*/nodejs* runtime)", m.Runtime)
	}
}

// runtimeFamily maps a RuntimeName to its type-generation language family.
func runtimeFamily(runtime string) string {
	r := strings.ToLower(runtime)
	switch {
	case strings.HasPrefix(r, "python") || strings.HasPrefix(r, "py"):
		return "python"
	case strings.HasPrefix(r, "node") || strings.HasPrefix(r, "js") || strings.HasPrefix(r, "ts"):
		return "node"
	default:
		return ""
	}
}

// typeSchema is the bounded JSON Schema view the generator needs (the funcd profile subset): a type (one
// name or the nullable [T, "null"] list), a closed record's properties + required set, an array's items,
// and a scalar enum. Constructs outside the profile (oneOf/anyOf/$ref) are gated away by contract.Check
// before types are ever generated.
type typeSchema struct {
	Type       contract.TypeField    `json:"type"`
	Properties map[string]typeSchema `json:"properties"`
	Required   []string              `json:"required"`
	Items      *typeSchema           `json:"items"`
	Enum       []json.RawMessage     `json:"enum"`
}

func parseTypeSchema(raw []byte) (typeSchema, error) {
	var s typeSchema
	if err := json.Unmarshal(raw, &s); err != nil {
		return typeSchema{}, err
	}
	return s, nil
}

// isRequired reports whether field name is in the schema's required set.
func (s typeSchema) isRequired(name string) bool {
	for _, r := range s.Required {
		if r == name {
			return true
		}
	}
	return false
}

// sortedProps returns the property names in a stable order so codegen is deterministic.
func (s typeSchema) sortedProps() []string {
	names := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}

const genHeader = "Generated by `funcdctl types` (ADR-0122) — DO NOT EDIT.\nDX-only: the platform never trusts these types; they drive editor autocomplete."

// ---- Python (.py module) --------------------------------------------------

func genPyi(in, out typeSchema, b Bindings) []byte {
	var buf strings.Builder
	for _, line := range strings.Split(genHeader, "\n") {
		buf.WriteString("# " + line + "\n")
	}
	buf.WriteString("from __future__ import annotations\n")
	buf.WriteString("from typing import Literal, TypedDict\n\n")
	buf.WriteString(pyiClass("FuncInput", in))
	buf.WriteString("\n")
	buf.WriteString(pyiClass("FuncOutput", out))
	buf.WriteString("\n")
	buf.WriteString(pyiBindings(b))
	return []byte(buf.String())
}

// pyiClass renders one TypedDict for an object schema; a non-object or nullable schema degrades to a
// comment + an alias to its type expression (the profile's void/scalar sides).
func pyiClass(name string, s typeSchema) string {
	if !isRecord(s) {
		return fmt.Sprintf("%s = %s  # non-record contract side\n", name, pyType(s))
	}
	var buf strings.Builder
	fmt.Fprintf(&buf, "class %s(TypedDict):\n", name)
	for _, prop := range s.sortedProps() {
		opt := ""
		if !s.isRequired(prop) {
			opt = "  # optional"
		}
		fmt.Fprintf(&buf, "    %s: %s%s\n", prop, pyType(s.Properties[prop]), opt)
	}
	return buf.String()
}

// isRecord reports a non-nullable object schema with properties, the side rendered as a named record type.
func isRecord(s typeSchema) bool {
	return s.Type.Primary() == "object" && !s.Type.Nullable() && len(s.Properties) > 0
}

// pyType maps a bounded JSON Schema node to a Python type expression; a nullable node is `T | None`.
func pyType(s typeSchema) string {
	if s.Type.Nullable() {
		return pyBaseType(s) + " | None"
	}
	return pyBaseType(s)
}

func pyBaseType(s typeSchema) string {
	switch s.Type.Primary() {
	case "string":
		return "str"
	case "integer":
		return "int"
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "null":
		return "None"
	case "array":
		if s.Items == nil {
			return "list"
		}
		return fmt.Sprintf("list[%s]", pyType(*s.Items))
	case "object":
		return "dict[str, object]"
	default:
		return "object"
	}
}

func pyiBindings(b Bindings) string {
	var buf strings.Builder
	buf.WriteString("class Bindings:\n")
	rows := bindingRows(b)
	if len(rows) == 0 {
		buf.WriteString("    pass  # no bindings declared\n")
		return buf.String()
	}
	for _, r := range rows {
		fmt.Fprintf(&buf, "    %s: Literal[%s]\n", r.field, strings.Join(quoteAll(r.aliases), ", "))
	}
	return buf.String()
}

// ---- Node (.d.ts) ---------------------------------------------------------

func genDts(in, out typeSchema, b Bindings) []byte {
	var buf strings.Builder
	for _, line := range strings.Split(genHeader, "\n") {
		buf.WriteString("// " + line + "\n")
	}
	buf.WriteString("\n")
	buf.WriteString(dtsType("FuncInput", in))
	buf.WriteString("\n")
	buf.WriteString(dtsType("FuncOutput", out))
	buf.WriteString("\n")
	buf.WriteString(dtsBindings(b))
	return []byte(buf.String())
}

// dtsType renders one interface for an object schema; a non-object or nullable side degrades to a type alias.
func dtsType(name string, s typeSchema) string {
	if !isRecord(s) {
		return fmt.Sprintf("export type %s = %s;\n", name, tsType(s))
	}
	var buf strings.Builder
	fmt.Fprintf(&buf, "export interface %s {\n", name)
	for _, prop := range s.sortedProps() {
		opt := ""
		if !s.isRequired(prop) {
			opt = "?"
		}
		fmt.Fprintf(&buf, "  %s%s: %s;\n", prop, opt, tsType(s.Properties[prop]))
	}
	buf.WriteString("}\n")
	return buf.String()
}

// tsType maps a bounded JSON Schema node to a TypeScript type expression; a nullable node is `T | null`.
func tsType(s typeSchema) string {
	if s.Type.Nullable() {
		return tsBaseType(s) + " | null"
	}
	return tsBaseType(s)
}

func tsBaseType(s typeSchema) string {
	switch s.Type.Primary() {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	case "array":
		if s.Items == nil {
			return "unknown[]"
		}
		if s.Items.Type.Nullable() {
			return fmt.Sprintf("(%s)[]", tsType(*s.Items))
		}
		return fmt.Sprintf("%s[]", tsType(*s.Items))
	case "object":
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}

func dtsBindings(b Bindings) string {
	var buf strings.Builder
	buf.WriteString("export interface FuncBindings {\n")
	rows := bindingRows(b)
	for _, r := range rows {
		fmt.Fprintf(&buf, "  %s: %s;\n", r.field, strings.Join(quoteAll(r.aliases), " | "))
	}
	buf.WriteString("}\n")
	return buf.String()
}

// ---- shared binding-context extraction ------------------------------------

type bindingRow struct {
	field   string
	aliases []string
}

// bindingRows collects the declared aliases per binding kind so both generators emit the same typed
// binding context (the alias is the capability handle the author passes to context.kv/blob/... ).
func bindingRows(b Bindings) []bindingRow {
	var rows []bindingRow
	add := func(field string, aliases []string) {
		if len(aliases) > 0 {
			rows = append(rows, bindingRow{field: field, aliases: aliases})
		}
	}
	kv := make([]string, 0, len(b.KV))
	for _, x := range b.KV {
		kv = append(kv, x.Alias)
	}
	add("kv", kv)
	blob := make([]string, 0, len(b.Blob))
	for _, x := range b.Blob {
		blob = append(blob, x.Alias)
	}
	add("blob", blob)
	cat := make([]string, 0, len(b.Catalogs))
	for _, x := range b.Catalogs {
		cat = append(cat, x.Alias)
	}
	add("catalogs", cat)
	links := make([]string, 0, len(b.Links))
	for _, x := range b.Links {
		links = append(links, x.Alias)
	}
	add("links", links)
	return rows
}

func quoteAll(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = fmt.Sprintf("%q", s)
	}
	return out
}
