package main

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"text/template"

	"github.com/spf13/cobra"

	"github.com/pyvvo/funcd/internal/platform/version"
	"github.com/pyvvo/funcd/internal/runtime/ctrmanager"
	"github.com/pyvvo/funcd/internal/runtime/provision"
)

// cniBinDir is the OS-standard CNI plugin dir provision.LayDown writes the CNI plugins into.
const cniBinDir = "/opt/cni/bin"

// Where the install/uninstall commands lay down the single systemd unit (ADR-0054/0026):
// funcd is THE service; the private containerd is funcd's managed child — there is NO
// separate containerd unit.
const (
	unitPath   = "/etc/systemd/system/funcd.service"
	funcdBin   = "/usr/local/bin/funcd"
	dataRoot   = "/var/lib/funcd"
	unitTmpl   = "funcd.service"
	unitContnt = `# funcd — single-binary serverless platform (ADR-0054/0026).
# funcd is the service; it starts + supervises its OWN private containerd as a child
# (the k3s/dockerd model) and imports its embedded curated images — NO separate
# containerd unit, NO registry. Pass --containerd <socket> to defer to a system daemon.
#
# Generated by ` + "`funcd install`" + ` — version {{.Version}} (commit {{.Commit}}).
[Unit]
Description=funcd — single-binary serverless platform
Documentation=https://github.com/pyvvo/funcd
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={{.Bin}}
Restart=on-failure
RestartSec=2
# Exit status 70 is safe mode's stop (ADR-0207): restarting would only repeat the crash loop.
RestartPreventExitStatus=70
# funcd needs root for the private containerd (cgroups, netns, mounts) — ADR-0011/0054.
User=root
Environment=FUNCD_DATA_DIR={{.DataRoot}}
StateDirectory=funcd
LimitNOFILE=1048576
# containerd is a managed CHILD of this process: stop signals funcd alone, so it stops its workers and then
# containerd, and systemd then kills whatever is left in the control group.
KillMode=mixed
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
`
)

// unitData is the template payload for the funcd.service unit (version-stamped — ADR-0026).
type unitData struct {
	Version  string
	Commit   string
	Bin      string
	DataRoot string
}

// renderUnit renders the version-stamped funcd.service unit text. Pure + cross-platform —
// the --print path and the real install both use it, so the printed unit is byte-identical
// to the installed one.
func renderUnit() (string, error) {
	t, err := template.New(unitTmpl).Parse(unitContnt)
	if err != nil {
		return "", fmt.Errorf("parse unit template: %w", err)
	}
	info := version.Get()
	var sb strings.Builder
	if err := t.Execute(&sb, unitData{
		Version: info.Version, Commit: info.Commit, Bin: funcdBin, DataRoot: dataRoot,
	}); err != nil {
		return "", fmt.Errorf("render unit: %w", err)
	}
	return sb.String(), nil
}

// newInstallCmd builds `funcd install [--print]` (ADR-0054, refines ADR-0026). --print is the
// non-gated, cross-platform dry-run: it renders the version-stamped funcd.service unit to out
// and touches NOTHING. The real install (write the unit, lay down crun + the private
// containerd, enable + start the unit) is Linux+root and is exercised in the deferred
// integration lane. scenario: one-service-install.
func newInstallCmd(out io.Writer) *cobra.Command {
	var printOnly bool
	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install funcd as a single systemd service (funcd manages containerd as its child)",
		Long: "install lays down crun + the private containerd and writes + enables ONE funcd.service " +
			"systemd unit (funcd is the service; containerd is its managed child — no separate unit). " +
			"It is idempotent. --print dry-runs: it prints the version-stamped unit and touches nothing.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			unit, err := renderUnit()
			if err != nil {
				return err
			}
			if printOnly {
				return printPlan(out, unit)
			}
			return runInstall(cmd.Context(), out, unit)
		},
	}
	cmd.Flags().BoolVar(&printOnly, "print", false,
		"dry-run: print the version-stamped funcd.service unit and exit, touching nothing")
	return cmd
}

// newUninstallCmd builds `funcd uninstall` (ADR-0054): reverses install — stop + disable the
// unit and remove it (idempotent). Linux+root; off Linux it reports the platform gate. The
// funcd data-root is left in place (operator data); `--purge` is a future option.
func newUninstallCmd(out io.Writer) *cobra.Command {
	return &cobra.Command{
		Use:   "uninstall",
		Short: "Remove the funcd systemd service (reverses install; idempotent)",
		Args:  cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runUninstall(out)
		},
	}
}

// requireLinuxRoot gates an op that manages the systemd unit (the real install/uninstall, `upgrade --unit`), which is
// Linux + root only. Off Linux or as a non-root user it returns a clear, actionable error; printHint points install
// and uninstall at the non-gated `install --print` dry-run.
func requireLinuxRoot(op string, printHint bool) error {
	offLinux, noRoot := "", ""
	if printHint {
		offLinux, noRoot = "; use --print to preview the unit", " (or use --print)"
	}
	if runtime.GOOS != "linux" {
		return fmt.Errorf("%s manages a systemd unit — Linux only (got %s)%s", op, runtime.GOOS, offLinux)
	}
	if os.Geteuid() != 0 {
		return fmt.Errorf("%s manages a systemd unit and needs root — re-run with sudo%s", op, noRoot)
	}
	return nil
}

// printPlan writes the version-stamped unit followed by the lay-down plan (what install WOULD
// download to where) and touches NOTHING — the no-touch dry-run (ADR-0056 scenario
// install-print-no-touch). Plan is pure (no net, no disk).
func printPlan(out io.Writer, unit string) error {
	if _, err := io.WriteString(out, unit); err != nil {
		return err
	}
	if _, err := io.WriteString(out, "\n# lay-down plan (funcd install would download):\n"); err != nil {
		return err
	}
	for _, line := range provision.Plan(ctrmanager.BinDir(), cniBinDir) {
		if _, err := fmt.Fprintf(out, "#   %s\n", line); err != nil {
			return err
		}
	}
	return nil
}

// runInstall writes the funcd.service unit, lays down the runtime binaries (crun + containerd +
// the CNI plugins, SHA-256-verified — ADR-0056), then enables + (re)starts the unit via systemd.
// funcd then starts its own private containerd as a child (no separate unit). Idempotent: writing
// the same unit, a present-version-matched lay-down, and `enable --now` are all safe to repeat.
// Linux+root only; the real path is exercised in the deferred integration lane.
func runInstall(ctx context.Context, out io.Writer, unit string) error {
	const op = "funcd install"
	if err := requireLinuxRoot(op, true); err != nil {
		return err
	}
	if err := os.WriteFile(unitPath, []byte(unit), 0o644); err != nil { //nolint:gosec // a systemd unit is world-readable by design
		return fmt.Errorf("%s: write %s: %w", op, unitPath, err)
	}
	if err := os.MkdirAll(dataRoot, 0o700); err != nil {
		return fmt.Errorf("%s: create data-root %s: %w", op, dataRoot, err)
	}
	// Lay down the SHA-256-verified runtime (crun/containerd into funcd's bin dir, CNI plugins
	// into /opt/cni/bin) — the temporary download stand-in for ADR-0054's bundled release.
	if err := provision.LayDown(ctx, ctrmanager.BinDir(), cniBinDir); err != nil {
		return fmt.Errorf("%s: lay down runtime: %w", op, err)
	}
	if _, err := systemctl("daemon-reload"); err != nil {
		return fmt.Errorf("%s: %w", op, err)
	}
	if _, err := systemctl("enable", "--now", "funcd.service"); err != nil {
		return fmt.Errorf("%s: %w", op, err)
	}
	_, _ = fmt.Fprintf(out, "installed and started funcd.service (%s)\n", unitPath)
	return nil
}

// runUninstall stops + disables the unit and removes it (idempotent — missing unit is fine).
// The funcd data-root is left in place (operator data). Linux+root only.
func runUninstall(out io.Writer) error {
	const op = "funcd uninstall"
	if err := requireLinuxRoot(op, true); err != nil {
		return err
	}
	_, _ = systemctl("disable", "--now", "funcd.service") // best-effort: not-loaded ⇒ already gone
	if err := os.Remove(unitPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("%s: remove %s: %w", op, unitPath, err)
	}
	_, _ = systemctl("daemon-reload")
	_, _ = fmt.Fprintf(out, "removed funcd.service (%s); data-root %s left in place\n", unitPath, dataRoot)
	return nil
}

// systemctl runs `systemctl <args...>` and returns its standard output (`show` is read, ADR-0207); a failure carries
// both outputs.
func systemctl(args ...string) ([]byte, error) {
	var stdout, stderr bytes.Buffer
	cmd := exec.Command("systemctl", args...)
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	if err := cmd.Run(); err != nil {
		return stdout.Bytes(), fmt.Errorf("systemctl %v: %w: %s%s", args, err, stdout.Bytes(), stderr.Bytes())
	}
	return stdout.Bytes(), nil
}
